server:
  port: 8080

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/authoritymanagement?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 500
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' #是用来验证数据库连接的查询语句（mysql）
      # validationQuery: select 'x' from dual #是用来验证数据库连接的查询语句（oracle）
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20

    redis:
      database: 0 #Redis数据库索引（默认为0）
      host: localhost #Redis服务器地址，请替换为自己的redis服务器地址
      port: 6379 #Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 5    # 连接池中的最大空闲连接
      redis.minIdle: 0  # 连接池中的最小空闲连接
      redis.maxWaitMillis: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      redis.testonBorrow: true  #在获取连接的时候检查有效性, 默认false

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.zt.sys./**/.entity

##pagehelper 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  # 默认false,当为true时，自动检验适合的数据库
  auto-dialect: true
  # 这个一定要加上，不然mysql和oracle分页两个只能用一个，另一个会报错，加上后，两中数据库分页都可以用了
  #auto-runtime-dialect: true
  page-size-zero: true
  returnPageInfo: check

logging:
  level:
    com.zt.sys.authority: debug

